import React, { useState, useMemo } from 'react';
import {
    View,
    Text,
    ScrollView,
    TouchableOpacity,
    StyleSheet,
    Alert,
    Share,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import Markdown from 'react-native-markdown-display';
import { MotiView, AnimatePresence } from 'moti';
import * as Clipboard from 'expo-clipboard';
import { useTheme, getThemeColors } from '@/lib/ThemeContext';
import { useFeedback } from '@/lib/feedback';
import type { ExamPrediction, PredictedQuestion } from '@/lib/store/types';

interface PredictionViewerProps {
    prediction: ExamPrediction;
    onClose: () => void;
}

export const PredictionViewer: React.FC<PredictionViewerProps> = ({ prediction, onClose }) => {
    const { isDarkMode } = useTheme();
    const colors = getThemeColors(isDarkMode);
    const { play, haptic } = useFeedback();

    const [expandedQuestions, setExpandedQuestions] = useState<Set<number>>(new Set());

    const reportData = prediction.report_data;
    const predictions = reportData?.predictions || [];

    // Group predictions by confidence level and assign display numbers
    const groupedPredictions = useMemo(() => {
        const high: (PredictedQuestion & { originalIndex: number; displayNumber: number })[] = [];
        const medium: (PredictedQuestion & { originalIndex: number; displayNumber: number })[] = [];
        const low: (PredictedQuestion & { originalIndex: number; displayNumber: number })[] = [];

        let currentNumber = 1;

        // Collect by category first to ensure correct sequential numbering for display
        const categories = {
            high: predictions.filter(q => q.confidence === 'high'),
            medium: predictions.filter(q => q.confidence === 'medium'),
            low: predictions.filter(q => q.confidence !== 'high' && q.confidence !== 'medium')
        };

        categories.high.forEach((q) => {
            const originalIndex = predictions.indexOf(q);
            high.push({ ...q, originalIndex, displayNumber: currentNumber++ });
        });

        categories.medium.forEach((q) => {
            const originalIndex = predictions.indexOf(q);
            medium.push({ ...q, originalIndex, displayNumber: currentNumber++ });
        });

        categories.low.forEach((q) => {
            const originalIndex = predictions.indexOf(q);
            low.push({ ...q, originalIndex, displayNumber: currentNumber++ });
        });

        return { high, medium, low };
    }, [predictions]);

    const toggleQuestion = (index: number) => {
        haptic('selection');
        setExpandedQuestions((prev) => {
            const next = new Set(prev);
            if (next.has(index)) {
                next.delete(index);
            } else {
                next.add(index);
            }
            return next;
        });
    };

    const handleCopy = async (text: string) => {
        await Clipboard.setStringAsync(text);
        haptic('success');
        Alert.alert('Copied', 'Answer copied to clipboard.', [{ text: 'OK' }]);
    };

    const handleShare = async () => {
        haptic('selection');

        // Use the memoized numbered predictions for consistency with UI
        const { high, medium, low } = groupedPredictions;

        const formatQuestions = (questions: typeof high, emoji: string, label: string) => {
            if (questions.length === 0) return '';
            const questionList = questions.map(q => `${q.displayNumber}. ${q.question}`).join('\n');
            return `${emoji} ${label}\n${questionList}\n\n`;
        };

        const shareText = `📚 ${prediction.title}\n${predictions.length} Predicted Question${predictions.length !== 1 ? 's' : ''}\n\n` +
            formatQuestions(high, '🔴', 'HIGH PRIORITY') +
            formatQuestions(medium, '🟡', 'MEDIUM PRIORITY') +
            formatQuestions(low, '🟢', 'LOWER PRIORITY') +
            `Generated by Brigo`;

        try {
            await Share.share({
                message: shareText,
            });
        } catch (error) {
            console.error('Share failed:', error);
        }
    };


    const getPriorityColor = (priority: 'high' | 'medium' | 'low') => {
        switch (priority) {
            case 'high': return '#ef4444';
            case 'medium': return '#f59e0b';
            case 'low': return '#22c55e';
        }
    };

    const getQuestionTypeIcon = (type: 'mcq' | 'short_answer' | 'essay'): keyof typeof Ionicons.glyphMap => {
        switch (type) {
            case 'mcq': return 'list-outline';
            case 'short_answer': return 'create-outline';
            case 'essay': return 'document-text-outline';
            default: return 'help-circle-outline';
        }
    };

    // Markdown styles
    const markdownStyles = useMemo(() => ({
        body: {
            color: colors.text,
            fontSize: 15,
            lineHeight: 22,
            fontFamily: 'Nunito-Regular',
        },
        bullet_list: {
            marginVertical: 4,
        },
        list_item: {
            marginVertical: 4,
        },
        strong: {
            fontWeight: '700' as const,
            color: '#9333ea',
            fontFamily: 'SpaceGrotesk-Bold',
        },
        em: {
            fontStyle: 'italic' as const,
        },
        code_inline: {
            backgroundColor: isDarkMode ? '#3a3a3c' : '#f0f0f0',
            paddingHorizontal: 6,
            paddingVertical: 2,
            borderRadius: 4,
            fontFamily: 'SpaceGrotesk-Medium',
            color: '#9333ea',
        },
    }), [colors, isDarkMode]);

    const renderHeader = () => (
        <View style={[styles.header, { borderBottomColor: colors.border }]}>
            <TouchableOpacity
                onPress={() => {
                    play('tap');
                    onClose();
                }}
                style={styles.closeButton}
                hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
            >
                <Ionicons name="chevron-back" size={26} color={colors.text} />
            </TouchableOpacity>
            <View style={styles.headerCenter}>
                <Text style={[styles.headerTitle, { color: colors.text }]}>
                    {prediction.title}
                </Text>
                <Text style={[styles.headerSubtitle, { color: colors.textSecondary }]}>
                    {predictions.length} Predicted Question{predictions.length !== 1 ? 's' : ''}
                </Text>
            </View>
            <TouchableOpacity
                onPress={handleShare}
                style={styles.shareButton}
                hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
            >
                <Ionicons name="share-outline" size={22} color={colors.text} />
            </TouchableOpacity>
        </View>
    );

    const renderQuestionCard = (q: PredictedQuestion & { originalIndex: number; displayNumber: number }, priority: 'high' | 'medium' | 'low') => {
        const isExpanded = expandedQuestions.has(q.originalIndex);
        const priorityColor = getPriorityColor(priority);

        return (
            <MotiView
                key={q.originalIndex}
                from={{ opacity: 0, translateY: 10 }}
                animate={{ opacity: 1, translateY: 0 }}
                transition={{ delay: q.originalIndex * 50 }}
            >
                <TouchableOpacity
                    style={[styles.questionCard, { backgroundColor: colors.surface, borderColor: colors.border }]}
                    onPress={() => toggleQuestion(q.originalIndex)}
                    activeOpacity={0.7}
                >
                    {/* Priority indicator bar */}
                    <View style={[styles.priorityBar, { backgroundColor: priorityColor }]} />

                    <View style={styles.cardContent}>
                        {/* Question header with type icon */}
                        <View style={styles.questionHeader}>
                            <View style={[styles.typeIcon, { backgroundColor: isDarkMode ? '#2a2a2c' : '#f0f0f2' }]}>
                                <Ionicons
                                    name={getQuestionTypeIcon(q.question_type)}
                                    size={16}
                                    color="#9333ea"
                                />
                            </View>
                            <Text
                                style={[styles.questionText, { color: colors.text }]}
                                numberOfLines={isExpanded ? undefined : 2}
                            >
                                <Text style={{ fontFamily: 'SpaceGrotesk-Bold', color: '#9333ea' }}>{q.displayNumber}. </Text>
                                {q.question}
                            </Text>
                        </View>

                        {/* Expandable answer */}
                        <AnimatePresence>
                            {isExpanded && (
                                <MotiView
                                    from={{ opacity: 0 }}
                                    animate={{ opacity: 1 }}
                                    exit={{ opacity: 0 }}
                                    transition={{ type: 'timing', duration: 200 }}
                                >
                                    <View style={[styles.answerContainer, { backgroundColor: colors.surfaceAlt }]}>
                                        <View style={styles.answerHeader}>
                                            <Text style={styles.answerLabel}>Answer</Text>
                                            <TouchableOpacity
                                                onPress={() => handleCopy(q.answer)}
                                                style={styles.copyButton}
                                                hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                                            >
                                                <Ionicons name="copy-outline" size={16} color="#9333ea" />
                                            </TouchableOpacity>
                                        </View>
                                        <Markdown style={markdownStyles}>
                                            {q.answer}
                                        </Markdown>
                                    </View>
                                </MotiView>
                            )}
                        </AnimatePresence>

                        {/* Expand indicator */}
                        <View style={styles.expandIndicator}>
                            <Ionicons
                                name={isExpanded ? 'chevron-up' : 'chevron-down'}
                                size={18}
                                color={colors.textMuted}
                            />
                        </View>
                    </View>
                </TouchableOpacity>
            </MotiView>
        );
    };

    const renderPrioritySection = (
        title: string,
        questions: (PredictedQuestion & { originalIndex: number; displayNumber: number })[],
        priority: 'high' | 'medium' | 'low'
    ) => {
        if (questions.length === 0) return null;

        const priorityColor = getPriorityColor(priority);

        return (
            <View style={styles.prioritySection}>
                <View style={styles.priorityHeader}>
                    <View style={[styles.priorityDot, { backgroundColor: priorityColor }]} />
                    <Text style={[styles.priorityTitle, { color: colors.text }]}>
                        {title}
                    </Text>
                    <Text style={[styles.priorityCount, { color: colors.textMuted }]}>
                        {questions.length}
                    </Text>
                </View>
                {questions.map((q) => renderQuestionCard(q, priority))}
            </View>
        );
    };

    return (
        <SafeAreaView style={{ flex: 1, backgroundColor: colors.background }} edges={['top']}>
            {renderHeader()}

            <ScrollView
                style={{ flex: 1 }}
                contentContainerStyle={styles.scrollContent}
                showsVerticalScrollIndicator={false}
            >
                {predictions.length > 0 ? (
                    <>
                        {renderPrioritySection('High Priority', groupedPredictions.high, 'high')}
                        {renderPrioritySection('Medium Priority', groupedPredictions.medium, 'medium')}
                        {renderPrioritySection('Lower Priority', groupedPredictions.low, 'low')}
                    </>
                ) : (
                    <View style={styles.emptyState}>
                        <Ionicons name="bulb-outline" size={48} color={colors.textMuted} />
                        <Text style={[styles.emptyText, { color: colors.textSecondary }]}>
                            No predictions available
                        </Text>
                    </View>
                )}
            </ScrollView>
        </SafeAreaView>
    );
};

const styles = StyleSheet.create({
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
    },
    closeButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    shareButton: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerCenter: {
        flex: 1,
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 17,
        fontFamily: 'Outfit-SemiBold',
        letterSpacing: -0.3,
    },
    headerSubtitle: {
        fontSize: 13,
        fontFamily: 'SpaceGrotesk-Medium',
        marginTop: 2,
    },
    scrollContent: {
        paddingTop: 16,
        paddingBottom: 40,
    },
    prioritySection: {
        marginBottom: 24,
    },
    priorityHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginBottom: 12,
    },
    priorityDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginRight: 10,
    },
    priorityTitle: {
        fontSize: 14,
        fontFamily: 'SpaceGrotesk-Bold',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    priorityCount: {
        fontSize: 13,
        fontFamily: 'SpaceGrotesk-Medium',
        marginLeft: 8,
    },
    questionCard: {
        marginHorizontal: 16,
        marginBottom: 10,
        borderRadius: 14,
        borderWidth: 1,
        overflow: 'hidden',
        flexDirection: 'row',
    },
    priorityBar: {
        width: 4,
    },
    cardContent: {
        flex: 1,
        padding: 14,
    },
    questionHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    typeIcon: {
        width: 28,
        height: 28,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        marginTop: 2,
    },
    questionText: {
        flex: 1,
        fontSize: 15,
        fontFamily: 'Outfit-Medium',
        lineHeight: 22,
    },
    answerContainer: {
        marginTop: 14,
        padding: 14,
        borderRadius: 10,
    },
    answerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    answerLabel: {
        fontSize: 11,
        fontFamily: 'SpaceGrotesk-Bold',
        color: '#9333ea',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    copyButton: {
        padding: 4,
    },
    expandIndicator: {
        alignItems: 'center',
        marginTop: 8,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 80,
    },
    emptyText: {
        fontSize: 16,
        fontFamily: 'SpaceGrotesk-Medium',
        marginTop: 12,
    },
});
